import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";


const geistSans = localFont({
    src: "../fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "../fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className="scroll-smooth">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-950`}
            >
                <div className="flex min-h-screen flex-col  max-w-screen-lg mx-auto ">
                    {children}
                    <footer className="max-w-screen-lg mx-auto w-full p-5">
                        <span className="text-zinc-400 text-sm">
                            @ 2024 Augusto Sousa
                        </span>
                    </footer>
                </div>
            </body>
        </html>
    );
}
