import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Projects from "./@projects/page";
import Home from "./@home/page";
import { Separator } from "@/components/ui/separator";
import About from "./@about/page";
import Contact from "./@contact/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen flex-col bg-zinc-950 ">
          <Home />
          <Separator className="bg-zinc-600" />
          <Projects />
          <Separator className="bg-zinc-600" />
          <About />
          <Separator className="bg-zinc-600" />
          <Contact />

          <footer className="max-w-screen-lg mx-auto w-full p-5">
            <span className="text-zinc-400 text-sm">
              @ 2024 Augusto Sousa
            </span>
          </footer>
        </div>
      </body>
    </html>
  );
}
